---
   
#set Linux SWAP usage command
   
 - name: set Linux SWAP usage command
   set_fact:
     swap_usage_cmd: "free | awk '/Swap/ { print 100*$3/$2 }'"

 - name: Collect Top CPU users for Linux server
   shell: 'ps aux --sort=%mem|head -20' 
   register: top_cpu_users
   failed_when: top_cpu_users.rc == 2
   changed_when: false
   ignore_errors: true
 - debug:
     msg: "output {{ top_cpu_users }}"

 - name: Collect Top memory users for Linux server
   shell: 'cat /proc/meminfo|head -20'
   register: top_mem_users
   failed_when: top_mem_users.rc == 2
   changed_when: false
   ignore_errors: true
 - debug:
     msg: "output {{ top_mem_users }}"


 - name: Collect largest swap space user using /proc for Linux server
   shell: |
     SUM=0;OVERALL=0;for DIR in `find /proc/ -maxdepth 1 -type d | egrep "^/proc/[0-9]"`;do PID=`echo $DIR | cut -d / -f 3`;PROGNAME=`ps -p $PID -o comm --no-headers`;for SWAP in `grep Swap: $DIR/smaps 2>/dev/null| awk "{ print $2 }"`;do let SUM=$SUM;done;echo "Swap used: $SUM - ($PROGNAME )";let OVERALL=$OVERALL+$SUM;SUM=0;done | sort -nr -k+3 | head -50
   register: swap_proc_users
   failed_when: swap_proc_users.rc == 2
   changed_when: false
   ignore_errors: true
 - debug:
     msg: "output {{ swap_proc_users }}"



 - name: Collect more /proc users information  for Linux server
   shell: |
     for file in /proc/*/status;do awk '/VmSwap|Name|VmSize/{printf "%-8s%16s%3s ",$1,$2,$3}END{ print ""}' $file;done|sort -n -rk 7|grep VmSwap | head -20
   register: swap_proc_users_more
   failed_when: swap_proc_users_more.rc == 2
   changed_when: false
   ignore_errors: true
 - debug:
     msg: "output {{ swap_proc_users_more }}"


 - name: preparing ticket log for linux server
   set_fact: 
     exec_message:
      "Top CPU users: {{ top_cpu_users.stdout }} \
       Top memory users: {{ top_mem_users.stdout }} \  
       /proc information: {{ swap_proc_users.stdout }} \ {{ swap_proc_users_more.stdout }}"
